/*
 * Created on 2018-09-11 ( Time 21:38:57 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.heroku.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "finserv__financialgoal__c"
 *
 * @author Rodrigo Torres
 *
 */

@Entity
@Table(name="finserv__financialgoal__c", schema="salesforce" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Goal.countAll", query="SELECT COUNT(x) FROM Goal x" )
} )
public class Goal implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    @Column(name="finserv__actualvalue__c")
    private Double     actualValue ;


    @Temporal(TemporalType.DATE)
    @Column(name="finserv__targetdate__c")
    private Date       targetDate ;


    @Column(name="finserv__targetvalue__c")
    private Double     targetValue ;


    @Column(name="finserv__type__c", length=255)
    private String     type ;


    @Column(name="name", length=80)
    private String     name         ;


    @Transient
    @JsonIgnore
    @Column(name="isdeleted")
    private Boolean    isdeleted    ;


    @Transient
    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp")
    private Date       systemmodstamp ;


    @Column(name="finserv__status__c", length=255)
    private String     status ;


    @Column(name="finserv__primaryowner__c", length=18)
    private String     owner ;


    @Column(name="external_id__c", length=255)
    private String     externalId ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate")
    private Date       createddate  ;


    @Column(name="sfid", length=18)
    private String     sfid         ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_lastop", length=32)
    private String     hcLastop     ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_err", length=2147483647)
    private String     hcErr        ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Goal()
    {
		super();
    }

    public Goal update(Goal a) {
		this.id = a.id;
        this.actualValue = a.actualValue;
        this.targetDate = a.targetDate;
        this.targetValue = a.targetValue;
        this.type = a.type;
        this.name = a.name;
        this.isdeleted = a.isdeleted;
        this.systemmodstamp = a.systemmodstamp;
        this.status = a.status;
        this.owner = a.owner;
        this.externalId = a.externalId;
        this.createddate = a.createddate;
        this.sfid = a.sfid;
        this.hcLastop = a.hcLastop;
        this.hcErr = a.hcErr;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id )
    {
        this.id = id ;
    }
    public Long getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : finserv__actualvalue__c ( float8 ) 


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(actualValue);
        sb.append("|");
        sb.append(targetDate);
        sb.append("|");
        sb.append(targetValue);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(isdeleted);
        sb.append("|");
        sb.append(systemmodstamp);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(owner);
        sb.append("|");
        sb.append(externalId);
        sb.append("|");
        sb.append(createddate);
        sb.append("|");
        sb.append(sfid);
        sb.append("|");
        sb.append(hcLastop);
        sb.append("|");
        sb.append(hcErr);
        return sb.toString(); 
    }

	public Double getActualValue() {
		return actualValue;
	}

	public void setActualValue(Double actualValue) {
		this.actualValue = actualValue;
	}

	public Date getTargetDate() {
		return targetDate;
	}

	public void setTargetDate(Date targetDate) {
		this.targetDate = targetDate;
	}

	public Double getTargetValue() {
		return targetValue;
	}

	public void setTargetValue(Double targetValue) {
		this.targetValue = targetValue;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getIsdeleted() {
		return isdeleted;
	}

	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

	public Date getSystemmodstamp() {
		return systemmodstamp;
	}

	public void setSystemmodstamp(Date systemmodstamp) {
		this.systemmodstamp = systemmodstamp;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getOwner() {
		return owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public String getExternalId() {
		return externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	public Date getCreateddate() {
		return createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	public String getSfid() {
		return sfid;
	}

	public void setSfid(String sfid) {
		this.sfid = sfid;
	}

	public String getHcLastop() {
		return hcLastop;
	}

	public void setHcLastop(String hcLastop) {
		this.hcLastop = hcLastop;
	}

	public String getHcErr() {
		return hcErr;
	}

	public void setHcErr(String hcErr) {
		this.hcErr = hcErr;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	} 

}