/*
 * Created on 2018-09-20 ( Time 17:58:42 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.heroku.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Persistent class for entity stored in table "goal_details"
 *
 * @author rtorres
 *
 */

@Entity
@Table(name="goal_details", schema="public" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="GoalDetails.countAll", query="SELECT COUNT(x) FROM GoalDetails x" )
} )
public class GoalDetails implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    @Column(name="amount", nullable=false)
    private Double     amount       ;


    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false)
    private Date       date         ;

    @JsonIgnore
    @Column(name="goalid", nullable=false, length=50)
    private String     goalid       ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public GoalDetails()
    {
		super();
    }

    public GoalDetails update(GoalDetails a) {
		this.id = a.id;
        this.amount = a.amount;
        this.date = a.date;
        this.goalid = a.goalid;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id )
    {
        this.id = id ;
    }
    public Long getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------

    //--- DATABASE MAPPING : amount ( float8 ) 
    public void setAmount( Double amount )
    {
        this.amount = amount;
    }
    public Double getAmount()
    {
        return this.amount;
    }

    //--- DATABASE MAPPING : date ( date ) 
    public void setDate( Date date )
    {
        this.date = date;
    }
    public Date getDate()
    {
        return this.date;
    }

    //--- DATABASE MAPPING : goalid ( varchar ) 
    public void setGoalid( String goalid )
    {
        this.goalid = goalid;
    }
    public String getGoalid()
    {
        return this.goalid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(amount);
        sb.append("|");
        sb.append(date);
        sb.append("|");
        sb.append(goalid);
        return sb.toString(); 
    } 

}