/*
 * Created on 2018-09-11 ( Time 21:38:57 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.heroku.entities;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "finserv__financialgoal__c"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="finserv__financialgoal__c", schema="salesforce" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Goal.countAll", query="SELECT COUNT(x) FROM Goal x" )
} )
public class Goal implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    @Column(name="finserv__actualvalue__c")
    private Double     finservActualvalueCustom ;


    @Temporal(TemporalType.DATE)
    @Column(name="finserv__targetdate__c")
    private Date       finservTargetdateCustom ;


    @Column(name="finserv__targetvalue__c")
    private Double     finservTargetvalueCustom ;


    @Column(name="finserv__type__c", length=255)
    private String     finservTypeCustom ;


    @Column(name="name", length=80)
    private String     name         ;


    @Transient
    @JsonIgnore
    @Column(name="isdeleted")
    private Boolean    isdeleted    ;


    @Transient
    @JsonIgnore
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="systemmodstamp")
    private Date       systemmodstamp ;


    @Column(name="finserv__status__c", length=255)
    private String     finservStatusCustom ;


    @Column(name="finserv__primaryowner__c", length=18)
    private String     finservPrimaryownerCustom ;


    @Column(name="external_id__c", length=255)
    private String     externalIdCustom ;


    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createddate")
    private Date       createddate  ;


    @Column(name="sfid", length=18)
    private String     sfid         ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_lastop", length=32)
    private String     hcLastop     ;


    @Transient
    @JsonIgnore
    @Column(name="_hc_err", length=2147483647)
    private String     hcErr        ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Goal()
    {
		super();
    }

    public Goal update(Goal a) {
		this.id = a.id;
        this.finservActualvalueCustom = a.finservActualvalueCustom;
        this.finservTargetdateCustom = a.finservTargetdateCustom;
        this.finservTargetvalueCustom = a.finservTargetvalueCustom;
        this.finservTypeCustom = a.finservTypeCustom;
        this.name = a.name;
        this.isdeleted = a.isdeleted;
        this.systemmodstamp = a.systemmodstamp;
        this.finservStatusCustom = a.finservStatusCustom;
        this.finservPrimaryownerCustom = a.finservPrimaryownerCustom;
        this.externalIdCustom = a.externalIdCustom;
        this.createddate = a.createddate;
        this.sfid = a.sfid;
        this.hcLastop = a.hcLastop;
        this.hcErr = a.hcErr;



		return a;
	}

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id )
    {
        this.id = id ;
    }
    public Long getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : finserv__actualvalue__c ( float8 ) 
    public void setFinservActualvalueCustom( Double finservActualvalueCustom )
    {
        this.finservActualvalueCustom = finservActualvalueCustom;
    }
    public Double getFinservActualvalueCustom()
    {
        return this.finservActualvalueCustom;
    }

    //--- DATABASE MAPPING : finserv__targetdate__c ( date ) 
    public void setFinservTargetdateCustom( Date finservTargetdateCustom )
    {
        this.finservTargetdateCustom = finservTargetdateCustom;
    }
    public Date getFinservTargetdateCustom()
    {
        return this.finservTargetdateCustom;
    }

    //--- DATABASE MAPPING : finserv__targetvalue__c ( float8 ) 
    public void setFinservTargetvalueCustom( Double finservTargetvalueCustom )
    {
        this.finservTargetvalueCustom = finservTargetvalueCustom;
    }
    public Double getFinservTargetvalueCustom()
    {
        return this.finservTargetvalueCustom;
    }

    //--- DATABASE MAPPING : finserv__type__c ( varchar ) 
    public void setFinservTypeCustom( String finservTypeCustom )
    {
        this.finservTypeCustom = finservTypeCustom;
    }
    public String getFinservTypeCustom()
    {
        return this.finservTypeCustom;
    }

    //--- DATABASE MAPPING : name ( varchar ) 
    public void setName( String name )
    {
        this.name = name;
    }
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : isdeleted ( bool ) 
    public void setIsdeleted( Boolean isdeleted )
    {
        this.isdeleted = isdeleted;
    }
    public Boolean getIsdeleted()
    {
        return this.isdeleted;
    }

    //--- DATABASE MAPPING : systemmodstamp ( timestamp ) 
    public void setSystemmodstamp( Date systemmodstamp )
    {
        this.systemmodstamp = systemmodstamp;
    }
    public Date getSystemmodstamp()
    {
        return this.systemmodstamp;
    }

    //--- DATABASE MAPPING : finserv__status__c ( varchar ) 
    public void setFinservStatusCustom( String finservStatusCustom )
    {
        this.finservStatusCustom = finservStatusCustom;
    }
    public String getFinservStatusCustom()
    {
        return this.finservStatusCustom;
    }

    //--- DATABASE MAPPING : finserv__primaryowner__c ( varchar ) 
    public void setFinservPrimaryownerCustom( String finservPrimaryownerCustom )
    {
        this.finservPrimaryownerCustom = finservPrimaryownerCustom;
    }
    public String getFinservPrimaryownerCustom()
    {
        return this.finservPrimaryownerCustom;
    }

    //--- DATABASE MAPPING : external_id__c ( varchar ) 
    public void setExternalIdCustom( String externalIdCustom )
    {
        this.externalIdCustom = externalIdCustom;
    }
    public String getExternalIdCustom()
    {
        return this.externalIdCustom;
    }

    //--- DATABASE MAPPING : createddate ( timestamp ) 
    public void setCreateddate( Date createddate )
    {
        this.createddate = createddate;
    }
    public Date getCreateddate()
    {
        return this.createddate;
    }

    //--- DATABASE MAPPING : sfid ( varchar ) 
    public void setSfid( String sfid )
    {
        this.sfid = sfid;
    }
    public String getSfid()
    {
        return this.sfid;
    }

    //--- DATABASE MAPPING : _hc_lastop ( varchar ) 
    public void setHcLastop( String hcLastop )
    {
        this.hcLastop = hcLastop;
    }
    public String getHcLastop()
    {
        return this.hcLastop;
    }

    //--- DATABASE MAPPING : _hc_err ( text ) 
    public void setHcErr( String hcErr )
    {
        this.hcErr = hcErr;
    }
    public String getHcErr()
    {
        return this.hcErr;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(finservActualvalueCustom);
        sb.append("|");
        sb.append(finservTargetdateCustom);
        sb.append("|");
        sb.append(finservTargetvalueCustom);
        sb.append("|");
        sb.append(finservTypeCustom);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(isdeleted);
        sb.append("|");
        sb.append(systemmodstamp);
        sb.append("|");
        sb.append(finservStatusCustom);
        sb.append("|");
        sb.append(finservPrimaryownerCustom);
        sb.append("|");
        sb.append(externalIdCustom);
        sb.append("|");
        sb.append(createddate);
        sb.append("|");
        sb.append(sfid);
        sb.append("|");
        sb.append(hcLastop);
        sb.append("|");
        sb.append(hcErr);
        return sb.toString(); 
    } 

}