/*
 * Created on 2018-09-24 ( Time 11:58:14 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.heroku.repository;

import com.heroku.entities.Accounttransaction ;

import org.springframework.data.repository.PagingAndSortingRepository;



/**
 * Spring JPA Repository for Accounttransaction
 * 
 * @author Rodrigo Torres (Heroku)
 *
 */
public interface AccounttransactionRepository extends PagingAndSortingRepository<Accounttransaction, Long> {
/*
		Accounttransaction findBySfid(String sfid);
*/

}