/*
 * Created on 2018-09-11 ( Time 21:38:57 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.heroku.repository;

import org.springframework.data.jpa.repository.JpaRepository;

import com.heroku.entities.Account ;



/**
 * Spring JPA Repository for Account
 * 
 * @author Rodrigo Torres (Heroku)
 *
 */
public interface AccountRepository extends JpaRepository<Account, Long> {

/*
		Account findBySfid(String sfid);
*/

}
