/*
 * Created on 2018-09-24 ( Time 11:58:14 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.heroku.repository;

import com.heroku.entities.FinancialAccount ;

import org.springframework.data.repository.PagingAndSortingRepository;



/**
 * Spring JPA Repository for FinancialAccount
 * 
 * @author Rodrigo Torres (Heroku)
 *
 */
public interface FinancialAccountRepository extends PagingAndSortingRepository<FinancialAccount, Long> {
/*
		FinancialAccount findBySfid(String sfid);
*/

}