/*
 * Created on 2018-09-20 ( Time 17:58:42 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.heroku.repository;

import com.heroku.entities.GoalDetails ;

import org.springframework.data.repository.PagingAndSortingRepository;



/**
 * Spring JPA Repository for GoalDetails
 * 
 * @author Rodrigo Torres (Heroku)
 *
 */
public interface GoalDetailsRepository extends PagingAndSortingRepository<GoalDetails, Long> {
/*
		GoalDetails findBySfid(String sfid);
*/

	Iterable<GoalDetails> findByGoalid(String goalid);
	
}