/*
 * Created on 2018-09-11 ( Time 21:38:57 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.heroku.repository;

import org.springframework.data.jpa.repository.JpaRepository;

import com.heroku.entities.Goal ;



/**
 * Spring JPA Repository for Goal
 * 
 * @author Rodrigo Torres (Heroku)
 *
 */
public interface GoalRepository extends JpaRepository<Goal, Long> {
/*
		Goal findBySfid(String sfid);
*/
//	Goal findOne(long id);
	
	Iterable<Goal> findByOwner(String owner);
	
}