/*
 * Created on 2018-09-11 ( Time 21:38:57 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.heroku.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import com.heroku.entities.Offer ;



/**
 * Spring JPA Repository for Offer
 * 
 * @author Rodrigo Torres (Heroku)
 *
 */
@Repository
public interface OfferRepository extends JpaRepository<Offer, Long> {
/*
		Offer findBySfid(String sfid);
*/
// Offer findOne(long id);
}