/*
 * Created on 2018-09-20 ( Time 12:34:31 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.heroku.repository;

import com.heroku.entities.Progress ;

import org.springframework.data.repository.PagingAndSortingRepository;



/**
 * Spring JPA Repository for Progress
 * 
 * @author Rodrigo Torres (Heroku)
 *
 */
public interface ProgressRepository extends PagingAndSortingRepository<Progress, Long> {
/*
		Progress findBySfid(String sfid);
*/
	
	Iterable<Progress> findByOwner(String owner);
	Iterable<Progress> findByOwnerAndStatus(String owner, String status);

}