/*
 * Created on 2018-09-20 ( Time 17:58:42 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.heroku.controllers;

import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.heroku.entities.GoalDetails;
import com.heroku.model.ResponseMessage;
import com.heroku.services.GoalDetailsService;

@CrossOrigin
@Controller
@RequestMapping(value="/api/v1/goaldetails")
public class GoalDetailsRestController {
	
	private static Logger logger = LoggerFactory.getLogger(GoalDetailsRestController.class);
	
	@Autowired
	private GoalDetailsService goaldetailsService;
		
	/*
	 * READ METHODS
	 */

	@RequestMapping(value= {"","/"}, method=RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage getAll() {

		ResponseMessage responseMessage = new ResponseMessage();
		responseMessage.setError(-1, "Goal id and member id is needed ");

		return responseMessage;
	}

	@RequestMapping(value="/page", method=RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage getPage(@RequestParam int page, @RequestParam int records) {

		if (logger.isDebugEnabled())
			logger.debug("GoalDetailsService -> getPage");
		
		ResponseMessage responseMessage = new ResponseMessage();
		try {
			responseMessage.setData(goaldetailsService.findAll(page, records));
		} catch (Exception e) {
			logger.error("GoalDetailsController -> getPage", e);
			responseMessage.setError(-1, "Unable to get page for GoalDetails: " + e.getMessage());
		}
		return responseMessage;
		
	}


//	@RequestMapping(value="/count", method=RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//	@ResponseBody
//	public ResponseMessage getCount() {
//
//		if (logger.isDebugEnabled())
//			logger.debug("GoalDetailsService -> getAll");
//		
//		ResponseMessage responseMessage = new ResponseMessage();
//		try {
//			responseMessage.setData(goaldetailsService.count());
//		} catch (Exception e) {
//			logger.error("GoalDetailsController -> getAll", e);
//			responseMessage.setError(-1, "Unable to get all GoalDetails: " + e.getMessage());
//		}
//		return responseMessage;
//		
//	}

//	@RequestMapping(value="/page", method=RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//	@ResponseBody
//	public ResponseMessage getPage(@RequestParam int page,@RequestParam int size) {
//
//		if (logger.isDebugEnabled())
//			logger.debug("GoalDetailsService -> getPage(" + page + "," + size + ")");
//		
//		ResponseMessage responseMessage = new ResponseMessage();
//		try {
//			responseMessage.setData(goaldetailsService.getPage(page, size));
//		} catch (Exception e) {
//			logger.error("GoalDetailsController -> getAll", e);
//			responseMessage.setError(-1, "Unable to get all GoalDetails: " + e.getMessage());
//		}
//		return responseMessage;
//		
//	}
	
//	@RequestMapping(value="/elements", method=RequestMethod.GET,
//			produces = MediaType.APPLICATION_JSON_VALUE)
//	@ResponseBody
//	public ResponseMessage getDropDownElements() {
//
//		if (logger.isDebugEnabled())
//			logger.debug("GoalDetailsService -> getDropDownElements");
//		
//		ResponseMessage responseMessage = new ResponseMessage();
//		try {
//			responseMessage.setData(goaldetailsService.getDropDownValues());
//		} catch (Exception e) {
//			logger.error("GoalDetailsController -> getDropDownElements", e);
//			responseMessage.setError(-1, "Unable to getDropDownElements for GoalDetails: " + e.getMessage());
//		}
//		return responseMessage;
//		
//	}

	@RequestMapping(value="/id/{id}", method=RequestMethod.GET,
			produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE})
	@ResponseBody
	public ResponseMessage getOne(@PathVariable Integer id) {
		if (logger.isDebugEnabled())
			logger.debug("GoalDetailsService -> getOne(" + id + ")");
		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			responseMessage.setData(goaldetailsService.get(id));
		} catch (Exception e) {
			logger.error("GoalDetailsController -> create", e);
			responseMessage.setError(-1,
					"Unable to create GoalDetails: " + id + ",Error:"  + e.getMessage());
		}
		
		return responseMessage;
	}

	@RequestMapping(value="/{goal}", method=RequestMethod.GET,
			produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.APPLICATION_XML_VALUE})
	@ResponseBody
	public ResponseMessage getGoalDetails(@PathVariable String goal) {
		if (logger.isDebugEnabled())
			logger.debug("GoalDetailsService -> getByOwnerAndGoal(" + goal + ")");
		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			responseMessage.setData(goaldetailsService.findByGoal(goal));
		} catch (Exception e) {
			logger.error("GoalDetailsController -> getByOwnerAndGoal", e);
			responseMessage.setError(-1,
					"Unable to create GoalDetails: " + goal + ",Error:"  + e.getMessage());
		}
		
		return responseMessage;
	}

	
	/*
	 * DML Methods
	 */
	@RequestMapping(value = "/create", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage create(@RequestBody GoalDetails element) {

		if (logger.isDebugEnabled())
			logger.debug("GoalDetailsService -> create:" + element);

		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			responseMessage.setData(goaldetailsService.create(element));
		} catch (Exception e) {
			logger.error("GoalDetailsController -> create", e);
			responseMessage.setError(-1,
					"Unable to create GoalDetails: " + element + ",Error:"  + e.getMessage());
		}
		
		return responseMessage;
	}

	@RequestMapping(value = "/edit/{id}", method = RequestMethod.PUT, produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage edit(@PathVariable Long id, @RequestBody GoalDetails element) {
		if (logger.isDebugEnabled())
			logger.debug("GoalDetailsService -> edit(" + id + "):" + element);

		ResponseMessage responseMessage = new ResponseMessage();
		
		try {
			element.setId(id);
			responseMessage.setData(goaldetailsService.create(element));
		} catch (Exception e) {
			logger.error("GoalDetailsController -> edit", e);
			responseMessage.setError(-1,
					"Unable to edit GoalDetails: " + element + ",Error:" + e.getMessage());
		}
		
		return responseMessage;
	}

	@RequestMapping(value="/delete/{id}", method=RequestMethod.DELETE, 
			produces = MediaType.APPLICATION_JSON_VALUE, consumes = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody
	public ResponseMessage delete(@PathVariable Long id) {

		if (logger.isDebugEnabled())
			logger.debug("GoalDetailsService -> delete(" + id + ")");

		ResponseMessage responseMessage = new ResponseMessage();
		try {
			goaldetailsService.delete(id);
		} catch (Exception e) {
			logger.error("GoalDetailsController -> delete", e);
			responseMessage.setError(-1, "Unable to delete GoalDetails: " + id + ",Error:"  + e.getMessage());
		}
		return responseMessage;
	}
	
	@ExceptionHandler(Exception.class)
	public @ResponseBody
	String handleException(Exception e, HttpServletResponse response) {
	    response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
	    return e.getMessage();
	}

}

