/*
 * Created on 2018-09-11 ( Time 21:38:57 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.heroku.exceptions;

public class AccountNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public AccountNotFoundException(Long id) {
		super("Account not found with id: " + id.toString());
	}

	public AccountNotFoundException(String account) {
		super("Account " + account + " not found!");
	}
}
