/*
 * Created on 2018-09-24 ( Time 11:58:14 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.heroku.exceptions;

public class FinancialAccountNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public FinancialAccountNotFoundException(Long id) {
		super("FinancialAccount not found with id: " + id.toString());
	}

	public FinancialAccountNotFoundException(String financialaccount) {
		super("FinancialAccount " + financialaccount + " not found!");
	}
}
