/*
 * Created on 2018-09-20 ( Time 17:58:42 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.heroku.exceptions;

public class GoalDetailsNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public GoalDetailsNotFoundException(Long id) {
		super("GoalDetails not found with id: " + id.toString());
	}

	public GoalDetailsNotFoundException(String goaldetails) {
		super("GoalDetails " + goaldetails + " not found!");
	}
}
