/*
 * Created on 2018-09-11 ( Time 21:38:57 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.heroku.exceptions;

public class GoalNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public GoalNotFoundException(Long id) {
		super("Goal not found with id: " + id.toString());
	}

	public GoalNotFoundException(String finservfinancialgoal) {
		super("Goal " + finservfinancialgoal + " not found!");
	}
}
