/*
 * Created on 2018-09-11 ( Time 21:38:57 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package com.heroku.exceptions;

public class OfferNotFoundException extends RuntimeException {

	private static final long serialVersionUID = -1L;

	public OfferNotFoundException(Long id) {
		super("Offer not found with id: " + id.toString());
	}

	public OfferNotFoundException(String offer) {
		super("Offer " + offer + " not found!");
	}
}
